### ISSUE TITLE
Estrutura e padrões da plataforma

### ISSUE THREAD

**Issue by JoseCage** [doesangueorg/doesangueweb#18]
Definir a estrutura de arquivos, pastas, funcionalidades e branching da plataforma de forma a se seguir um padrão para o desenvolvimento. O que ajudaria em manter o código padronizado e limpo (💯) e facilitar os desenvolvedores, designer/webdesigners que queiram colaborar no desenvolvimento poder facilmente entender e se adaptar ao  WorkFlow.

- [x] Definir padrões de código baseado nos guias do [PSR](http://www.php-fig.org/psr)

- [x] Definir estrutura de ficheiros específicos (Backend, Frontend, assets) para facilitar na manutenção.

🆘  :world_map:

**Comment by vinicius73** [comment]
Manter o código, tabelas e entidades em inglês ajuda nisso.
Também permite que todo um mundo de desenvolvedores possam ajudar no projeto.

**Comment by vinicius73** [comment]
Outra possibilidade, é manter dois projetos.
- API
- Aplicação

Isso permite uma fácil integração entre devs front-end e devs back-end, além de abrir possibilidades para futuras aplicações mobile.

**Comment by JoseCage** [comment]
Certo @vinicius73 (Grande Professor)..

No caso, sugere que esteja separado a API e a aplicação? Não percebi bem nesse aspeto..

De qualquer forma, conforme se falava na #1 um dos pontos é exatamente ter uma API, forma que facilitaria outros sistemas a abstrair dados da plataforma caso alguma queira.

**Comment by JoseCage** [comment]
Concordo na parte de deixar em inglês para facilitar a internacionalização..

Mas quanto a isso não terá pessoas  (no caso quem fala inglês por exemplo) com dificuldade em entender o projeto pelo nome "Doe Sangue"?

Acho que pode se manter o nome em PT e aplicar o inglês na parte da infra estrutura/código..

**Comment by vinicius73** [comment]
Sim, não tem que mudar o nome do projeto, só o código e entidades.

**Comment by vinicius73** [comment]
Eu acho que esse é um projeto com grande potencial
Sendo assim seria bom criar uma organização no GitHub, fica mais fácil de organizar o projeto e membros dele.

A ideia é ter 2 repositórios
- **doesangue-web** (client HTML/SPA)
- **doesangue-api** (Api que será consumida pelo client)

Isso abre possibilidades para outros repositórios, como **doesangue-mobile** mantendo tudo organizado e documentado.

Além de ser mais fácil de contribuir assim (um dev front-end pode focar só no front-end por exemplo) abre inúmeras possibilidades.
Serve até mesmo como fonte de aprendizado para quem não esta acostumado com projetos open-source

**Comment by JoseCage** [comment]
Obrigado novamente pela sugestão..

Estou criando a Org e transferindo o repo..

Valeu milhões ter publicado lá no slack..

**Comment by JoseCage** [comment]
Feito @vinicius73 

Movi o repositório para [doesangueorg](https://github.com/orgs/doesangueorg) tal como sugerido.

**Comment by JoseCage** [comment]
Algum feedback @vinicius73 ??
