### ISSUE TITLE
Lista de tarefas

### ISSUE THREAD

**Issue by rafa-acioly** [doesangueorg/doesangueweb#20]
Seria possível criar alguns Cards em `Projects` para saber quais tarefas estão pendentes?

**Comment by JoseCage** [comment]
É para já @rafa-acioly 

Esta questão já está mesmo no escopo.. #18

**Comment by JoseCage** [comment]
@rafa Dá uma olhada na lista de projetos. Sugestões e correções são bem vindas..

**Comment by JoseCage** [comment]
Para melhor organização todas tasks foram movidas na aba projetos..
